### ISSUE TITLE
Image Issues

### ISSUE THREAD

**Issue by Apolyonic** [erikas-taroza/redshelf_downloader#9]
For the most part. This works really well. 
I super appreciate this, because I loath the redshelf platform....

I am curious, if there is anything that can be done to help the output result be more similar to the actual book.

It seems to very because each book is slightly different. For example, my last book had the book rendered as JPG, and that made it easy to scrape, but the XML protected books seem to give me more troubles.

It appears to be grabbing images, but not putting them into the HTML, or the pdf.

Is there a way to correct this?
Hopefully some of the images below can help diagnose.

Thanks again!

![image](https://github.com/user-attachments/assets/8cf90eb7-5f99-48db-af2b-97dcf58f593e)
![image](https://github.com/user-attachments/assets/5f43fc70-2059-4df9-822a-3b67026cbb45)
![image](https://github.com/user-attachments/assets/e33c1583-c1a2-4450-9bc2-1392cdfb2e44)
![image](https://github.com/user-attachments/assets/9955fd01-8ddf-4648-bc0d-fa36d5d07035)
![image](https://github.com/user-attachments/assets/ce68dcd1-7232-402d-a602-fff56573dcbe)
![image](https://github.com/user-attachments/assets/a017b792-740d-4eab-808e-07fd56b55852)

**Comment by erikas-taroza** [comment]
My apologies! It seems like the paths for the downloaded resources are incorrect. I believe I have fixed the problem. Please run `git pull` to update and let me know how it goes.

**Comment by Apolyonic** [comment]
Wow - Real MVP, near real time updates and bug fixes.
I'll let you know, give me a few moments to check it out.

**Comment by Apolyonic** [comment]
AHHH you fixed it! 
Nice job!
![image](https://github.com/user-attachments/assets/9ed290e1-f3bb-47a1-bf70-1478223e2234)

The PDF doesn't seem to output very friendly to some of the characters, but that's likely due to the code generating the PDF's, not your code. 
![image](https://github.com/user-attachments/assets/5ba03100-e92d-406e-9ca0-ae892e2deb3d)
![image](https://github.com/user-attachments/assets/1238d9e3-0a79-4c4d-ac30-8a560bad4846)

Wonderful work Erikas.
Thank you!

**Comment by erikas-taroza** [comment]
No problem.

Yeah I have the same problem with my books. Some characters aren't rendered correctly. I already have an issue for it (#2).

Glad it rendered well for the most part.

**Comment by Apolyonic** [comment]
If you're willing to pursue this further, I would like to offer a suggestion; what might be more helpful for some is just to allow the browser to create the PDF output, 
So combine the HTML files into a single file, with the annoying overflow-y hidden set to auto in the base CSS file.
This would probably allow you to eliminate the bug from the pdf combiner that you're using.
